apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.config.backend.springProfilesActive | quote }}
  SPRING_APPLICATION_NAME: {{ .Values.config.backend.springApplicationName | quote }}
  SPRING_CACHE_TYPE: {{ .Values.config.backend.springCacheType | quote }}
  POSTGRES_HOST: {{ .Values.config.backend.postgresHost | quote }}
  POSTGRES_PORT: {{ .Values.config.backend.postgresPort | quote }}
  REDIS_HOST: {{ .Values.config.backend.redisHost | quote }}
  REDIS_PORT: {{ .Values.config.backend.redisPort | quote }}
  GEMINI_API_URL: {{ .Values.config.backend.geminiApiUrl | quote }}
